#print("Hello", "Saurabh", 2+2, True, 3*5)
print("Hi, My name is Saurabh", "Mehta")
print("Hi", "Saurabh", "Mehta",sep="-", end="")
print("Hi", "Saurabh", "Mehta", end="\t")
print("Hi", "Saurabh", "Mehta")
